# Generated by Django 3.0.2 on 2020-10-14 18:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holiday', models.CharField(max_length=50, verbose_name='С каким праздником поздравляем')),
                ('name', models.CharField(max_length=50, verbose_name='Ваше имя')),
                ('tel', models.CharField(max_length=50, verbose_name='Телефон')),
                ('Email', models.EmailField(max_length=50, verbose_name='Емейл')),
                ('message', models.CharField(max_length=500, verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Сообщение пользователя',
                'verbose_name_plural': 'Сообщения пользователей',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_title', models.CharField(max_length=250, verbose_name='Название раздела')),
                ('description', models.TextField(verbose_name='Описание раздела')),
                ('topic_photo', models.ImageField(blank=True, default='', upload_to='images', verbose_name='Фото')),
                ('topic_slug', models.SlugField(max_length=70, unique=True)),
            ],
            options={
                'verbose_name': 'раздел',
                'verbose_name_plural': 'разделы',
            },
        ),
        migrations.CreateModel(
            name='Stih',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField(verbose_name='Описание заказа')),
                ('stih_title', models.CharField(max_length=250, verbose_name='Название')),
                ('stih_text', models.TextField(verbose_name='Текст')),
                ('stih_photo', models.ImageField(blank=True, default='', upload_to='images', verbose_name='Фото')),
                ('stih_slug', models.SlugField(max_length=70, unique=True)),
                ('dateUploaded', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Дата обновления')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stihinazakaz.Topic')),
            ],
            options={
                'verbose_name': 'стихотворение',
                'verbose_name_plural': 'стихи',
                'ordering': ['-dateUploaded'],
            },
        ),
    ]
