# Generated by Django 3.0.2 on 2020-10-15 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stihinazakaz', '0002_feedback2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedback2',
            options={'verbose_name': 'Сообщение пользователя2', 'verbose_name_plural': 'Сообщения пользователей2'},
        ),
        migrations.AddField(
            model_name='feedback2',
            name='adresat',
            field=models.CharField(blank=True, max_length=500, verbose_name='Кого поздравляем, ФИО поздравляемого, работа, должность'),
        ),
    ]
