# Generated by Django 3.0.2 on 2020-10-15 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stihinazakaz', '0003_auto_20201015_0800'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback2',
            name='age',
            field=models.CharField(blank=True, max_length=50, verbose_name='Возраст поздравляемого'),
        ),
    ]
