# Generated by Django 3.0.2 on 2020-10-15 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stihinazakaz', '0004_feedback2_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback2',
            name='kem_prihodit',
            field=models.CharField(blank=True, max_length=50, verbose_name='Кем он вам приходится'),
        ),
    ]
