# Generated by Django 3.0.2 on 2020-10-15 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stihinazakaz', '0005_feedback2_kem_prihodit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback2',
            name='age',
            field=models.IntegerField(blank=True, verbose_name='Возраст поздравляемого'),
        ),
    ]
