# Generated by Django 3.0.2 on 2020-10-15 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stihinazakaz', '0007_auto_20201015_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback2',
            name='you',
            field=models.CharField(choices=[('ty', 'Ты'), ('vy', 'Вы')], default='ty', max_length=2),
        ),
        migrations.AlterField(
            model_name='feedback2',
            name='age',
            field=models.IntegerField(blank=True, verbose_name='Возраст поздравляемого'),
        ),
    ]
