# Generated by Django 3.0.2 on 2020-10-15 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stihinazakaz', '0011_auto_20201015_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback2',
            name='about',
            field=models.TextField(blank=True, verbose_name='Охарактеризуйте поздравляемого. Расскажите о нем: семья, работа, друзья, хобби, характер, отношения с близкими. Интересные случаи из жизни'),
        ),
    ]
