# Generated by Django 3.0.2 on 2020-10-15 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stihinazakaz', '0013_feedback2_wishes'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback2',
            name='style',
            field=models.CharField(blank=True, choices=[('lir', 'Лирическом'), ('uva', 'Уважительном'), ('shu', 'Шуточном'), ('vos', 'Восхваляющем')], max_length=3),
        ),
        migrations.AlterField(
            model_name='feedback2',
            name='wishes',
            field=models.CharField(blank=True, max_length=300, verbose_name='Ваши пожелания'),
        ),
    ]
