# Generated by Django 3.0.2 on 2020-10-15 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stihinazakaz', '0014_auto_20201015_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback2',
            name='style',
            field=models.CharField(blank=True, choices=[('uva', 'Уважительном'), ('shu', 'Шуточном'), ('vos', 'Восхваляющем'), ('lir', 'Лирическом')], max_length=3),
        ),
        migrations.AlterField(
            model_name='feedback2',
            name='you',
            field=models.CharField(blank=True, choices=[('ty', 'Ты'), ('vy', 'Вы')], max_length=2),
        ),
    ]
