# Generated by Django 3.0.2 on 2020-10-15 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stihinazakaz', '0015_auto_20201015_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback2',
            name='how_many',
            field=models.CharField(blank=True, choices=[('one', 'От одного человека'), ('few', 'От нескольких')], max_length=3),
        ),
    ]
