# Generated by Django 3.0.2 on 2020-10-15 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stihinazakaz', '0017_auto_20201015_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback2',
            name='Email',
            field=models.EmailField(blank=True, max_length=50, verbose_name='Емейл'),
        ),
        migrations.AlterField(
            model_name='feedback2',
            name='holiday',
            field=models.CharField(blank=True, max_length=50, verbose_name='С каким праздником поздравляем'),
        ),
        migrations.AlterField(
            model_name='feedback2',
            name='name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Ваше имя'),
        ),
        migrations.AlterField(
            model_name='feedback2',
            name='tel',
            field=models.CharField(blank=True, max_length=50, verbose_name='Телефон'),
        ),
    ]
