# Generated by Django 3.0.2 on 2020-10-15 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stihinazakaz', '0018_auto_20201015_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback2',
            name='age',
            field=models.CharField(blank=True, max_length=50, verbose_name='Возраст поздравляемого'),
        ),
        migrations.AlterField(
            model_name='feedback2',
            name='holiday',
            field=models.CharField(blank=True, max_length=50, verbose_name='Праздник'),
        ),
    ]
