# Generated by Django 3.0.2 on 2020-10-15 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stihinazakaz', '0020_auto_20201015_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback2',
            name='about',
            field=models.TextField(blank=True, verbose_name='Инфо для стихов'),
        ),
    ]
