# Generated by Django 3.0.2 on 2020-10-16 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stihinazakaz', '0021_auto_20201015_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback2',
            name='adresat',
            field=models.CharField(blank=True, max_length=500, verbose_name='Кому'),
        ),
    ]
