# Generated by Django 3.0.2 on 2020-10-18 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stihinazakaz', '0023_feedback2_on_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback2',
            name='on_site',
            field=models.CharField(blank=True, choices=[('yes', 'Да'), ('no', 'Нет')], max_length=3),
        ),
    ]
