# Generated by Django 3.0.2 on 2020-10-20 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stihinazakaz', '0024_auto_20201018_0752'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
